# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-15 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
                ('c_isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.CharField(max_length=20)),
                ('g_name', models.CharField(max_length=30)),
                ('g_pic', models.CharField(max_length=30)),
                ('g_jianjie', models.CharField(max_length=200)),
                ('g_color', models.CharField(max_length=10)),
                ('g_colorType', models.CharField(max_length=20)),
                ('g_version', models.CharField(max_length=30)),
                ('g_type', models.CharField(max_length=30)),
                ('g_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('g_click', models.IntegerField()),
                ('g_kucun', models.IntegerField()),
                ('g_isDelete', models.BooleanField(default=False)),
                ('g_cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CompanyInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20)),
                ('u_sex', models.BooleanField(default=0)),
                ('u_phone', models.IntegerField(max_length=20)),
                ('u_age', models.IntegerField(max_length=5)),
            ],
        ),
    ]
