# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-25 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190125_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_name', models.CharField(max_length=20)),
                ('adv_pic', models.CharField(max_length=100)),
                ('adv_content', models.CharField(max_length=100)),
            ],
        ),
    ]
