# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-30 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190130_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='UserInfo',
            name='u_age'
        )
    ]
