# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-30 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190130_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='UserInfo',
            name='u_id',
            field=models.CharField(max_length=1000),
        ),
    ]
