# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-30 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190130_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='UserInfo',
            name='u_createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]