# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190419_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(max_length=20),
        ),
    ]
