# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-19 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190419_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
