# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-24 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190419_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=20)),
                ('indexweb', models.CharField(max_length=10000)),
                ('context', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(max_length=30)),
                ('click', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('user_source', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=30)),
                ('context', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=10)),
                ('colorType', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=30)),
                ('kucun', models.IntegerField()),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Goods')),
            ],
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='g_cp',
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.DeleteModel(
            name='GoodsInfo',
        ),
    ]
