# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-24 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190424_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='isDelete',
            field=models.BooleanField(default=True),
        ),
    ]
