# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-24 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190424_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='cp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Company'),
        ),
    ]
