# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-24 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190424_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsdetail',
            name='colorType',
        ),
    ]
