# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-24 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_goodsdetail_colortype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsdetail',
            name='kucun',
        ),
        migrations.AddField(
            model_name='goodsdetail',
            name='Stock',
            field=models.IntegerField(default=1000),
        ),
    ]
