# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-25 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190424_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='click',
            field=models.IntegerField(default=0),
        ),
    ]
