# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-25 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190425_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
