# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-26 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190425_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdetail',
            name='color',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='version',
            field=models.CharField(max_length=1000),
        ),
    ]
