# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-26 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190426_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsdetail',
            old_name='Stock',
            new_name='stock',
        ),
    ]
