# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-26 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190426_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
    ]
