# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-07 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190426_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscontent',
            name='good',
            field=models.CharField(max_length=20),
        ),
    ]
