# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-08 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190507_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsdetail',
            name='parttype',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
