# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-08 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_goodsdetail_parttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Goods')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.MyUser')),
            ],
        ),
    ]
