# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190508_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='version',
            field=models.CharField(default='', max_length=100),
        ),
    ]
