# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_order_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Order'),
        ),
    ]
