# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_orderinfo_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order'),
        ),
    ]
