# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20190509_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
