# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_order_is_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
